/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.alitheiavison.devdevil.everything

import org.alitheiavison.devdevil.everything.parser.FlagOfDword

fun main(args: Array<String>) {

}
